/**
 * 週次レポートモジュール
 * Markdownフォーマットでの週次サマリー生成、プレビュー、コピー、ダウンロードを管理する
 */

const WeeklyReport = (() => {
    let currentMarkdown = '';

    /**
     * 週次レポートのMarkdownを生成する
     * @param {Object} data - レポートデータ
     * @returns {string} Markdown形式のレポート
     */
    function generateMarkdown(data) {
        const lines = [];
        lines.push(`# 📊 週次レポート`);
        lines.push(`**期間**: ${data.period}`);
        lines.push('');
        lines.push(`---`);
        lines.push('');

        // サマリー
        lines.push(`## 🎯 今週のサマリー`);
        lines.push('');
        lines.push(`| 指標 | 値 |`);
        lines.push(`|---|---|`);
        lines.push(`| 総コミット数 | **${data.totalCommits}** |`);
        lines.push(`| コーディング時間 | **${data.totalHours}h** |`);
        lines.push(`| 連続コミット日数 | **${data.streak}日** 🔥 |`);
        lines.push(`| ピーク時間帯 | ${data.peakHour} |`);
        lines.push(`| 作業BGMトップ | ${data.topGenre} 🎵 |`);
        lines.push(`| 平均エネルギー | ${data.energyAvg}% |`);
        lines.push('');

        // 言語別
        lines.push(`## 💻 使用言語`);
        lines.push('');
        data.topLanguages.forEach(lang => {
            const bar = '█'.repeat(Math.floor(lang.percentage / 5)) + '░'.repeat(20 - Math.floor(lang.percentage / 5));
            lines.push(`- **${lang.name}** \`${bar}\` ${lang.percentage}%`);
        });
        lines.push('');

        // リポジトリ
        lines.push(`## 📁 アクティブリポジトリ`);
        lines.push('');
        data.topRepos.forEach((repo, i) => {
            const medal = ['🥇', '🥈', '🥉'][i] || '  ';
            lines.push(`${medal} **${repo.name}** — ${repo.commits} commits`);
        });
        lines.push('');

        // 成果
        lines.push(`## 🏆 今週の成果`);
        lines.push('');
        data.achievements.forEach(a => {
            lines.push(`- ${a}`);
        });
        lines.push('');

        // 改善点
        lines.push(`## 💡 改善ポイント`);
        lines.push('');
        data.improvements.forEach(imp => {
            lines.push(`- ${imp}`);
        });
        lines.push('');

        lines.push(`---`);
        lines.push(`*Generated by DevHabit Dashboard*`);

        return lines.join('\n');
    }

    /**
     * MarkdownをHTMLに変換する（簡易パーサー）
     * @param {string} md - Markdown文字列
     * @returns {string} HTML文字列
     */
    function markdownToHtml(md) {
        let html = md;

        // ヘッダー
        html = html.replace(/^### (.+)$/gm, '<h3>$1</h3>');
        html = html.replace(/^## (.+)$/gm, '<h2>$1</h2>');
        html = html.replace(/^# (.+)$/gm, '<h1>$1</h1>');

        // 水平線
        html = html.replace(/^---$/gm, '<hr>');

        // テーブル
        html = html.replace(/^\|(.+)\|$/gm, (match) => {
            const cells = match.split('|').filter(c => c.trim());
            if (cells.every(c => /^[-]+$/.test(c.trim()))) {
                return ''; // 区切り行はスキップ
            }
            const row = cells.map(c => `<td>${c.trim()}</td>`).join('');
            return `<tr>${row}</tr>`;
        });
        // テーブル行をtableで囲む
        html = html.replace(/((?:<tr>.+<\/tr>\n?)+)/g, '<table>$1</table>');

        // 太字
        html = html.replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>');

        // インラインコード
        html = html.replace(/`([^`]+)`/g, '<code>$1</code>');

        // リスト
        html = html.replace(/^- (.+)$/gm, '<li>$1</li>');
        html = html.replace(/((?:<li>.+<\/li>\n?)+)/g, '<ul>$1</ul>');

        // 段落
        html = html.replace(/^(?!<[hultdhr])(.+)$/gm, '<p>$1</p>');

        // 空行を削除
        html = html.replace(/<p>\s*<\/p>/g, '');

        return html;
    }

    /**
     * レポートを生成してUIに表示する
     */
    function generate() {
        const data = MockData.getWeeklyReportData();
        currentMarkdown = generateMarkdown(data);

        const previewEl = document.getElementById('report-preview');
        const rawEl = document.getElementById('report-raw');
        const placeholderEl = document.getElementById('report-placeholder');
        const footerEl = document.getElementById('report-footer');
        const copyBtn = document.getElementById('btn-copy-report');
        const downloadBtn = document.getElementById('btn-download-report');

        // プレビュー表示
        previewEl.innerHTML = markdownToHtml(currentMarkdown);
        previewEl.style.display = 'block';
        rawEl.textContent = currentMarkdown;
        placeholderEl.style.display = 'none';
        footerEl.style.display = 'block';

        // ボタンを有効化
        copyBtn.disabled = false;
        downloadBtn.disabled = false;

        // フェードインアニメーション
        previewEl.style.opacity = '0';
        previewEl.style.transform = 'translateY(10px)';
        requestAnimationFrame(() => {
            previewEl.style.transition = 'opacity 0.5s ease, transform 0.5s ease';
            previewEl.style.opacity = '1';
            previewEl.style.transform = 'translateY(0)';
        });
    }

    /**
     * Markdownをクリップボードにコピーする
     */
    async function copyToClipboard() {
        if (!currentMarkdown) return;
        try {
            await navigator.clipboard.writeText(currentMarkdown);
            const btn = document.getElementById('btn-copy-report');
            const originalHTML = btn.innerHTML;
            btn.innerHTML = '<i data-lucide="check"></i><span>コピー済み！</span>';
            lucide.createIcons();
            setTimeout(() => {
                btn.innerHTML = originalHTML;
                lucide.createIcons();
            }, 2000);
        } catch (err) {
            console.error('クリップボードへのコピーに失敗:', err);
        }
    }

    /**
     * MarkdownファイルとしてダウンロードするuserAgentに
     */
    function downloadMarkdown() {
        if (!currentMarkdown) return;
        const blob = new Blob([currentMarkdown], { type: 'text/markdown;charset=utf-8' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `weekly-report-${new Date().toISOString().split('T')[0]}.md`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
    }

    /**
     * プレビューとRaw表示を切り替える
     */
    function toggleRawView() {
        const previewEl = document.getElementById('report-preview');
        const rawEl = document.getElementById('report-raw');
        const toggleBtn = document.getElementById('btn-toggle-raw');

        if (rawEl.style.display === 'none') {
            rawEl.style.display = 'block';
            previewEl.style.display = 'none';
            toggleBtn.innerHTML = '<i data-lucide="eye"></i><span>プレビュー表示</span>';
        } else {
            rawEl.style.display = 'none';
            previewEl.style.display = 'block';
            toggleBtn.innerHTML = '<i data-lucide="code-2"></i><span>Markdown表示</span>';
        }
        lucide.createIcons();
    }

    /**
     * イベントリスナーを設定する
     */
    function bindEvents() {
        document.getElementById('btn-generate-report').addEventListener('click', generate);
        document.getElementById('btn-copy-report').addEventListener('click', copyToClipboard);
        document.getElementById('btn-download-report').addEventListener('click', downloadMarkdown);
        document.getElementById('btn-toggle-raw').addEventListener('click', toggleRawView);
    }

    /**
     * 週次レポートセクションを初期化する
     */
    function init() {
        bindEvents();
    }

    return { init, generate };
})();
